# Generated by Django 3.2.12 on 2022-04-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Issue_a', models.CharField(max_length=20)),
                ('Issue_b', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.vote')),
            ],
        ),
    ]
